### ISSUE TITLE
Failed Database Table 3d.z_prod

### ISSUE THREAD

**Issue by jgrabitzky** [squancy/zaccord#31]
Hi,

Great Work and thanks for your comment from my prev post.

I missing a database table 3d.z_prod

(node:126954) UnhandledPromiseRejectionWarning: Error: ER_NO_SUCH_TABLE: Table '3d.z_prod' doesn't exist

it is not in the database.sql dump.

where is the directory e-invoice?
error: ENOENT: no such file or directory, open 'e-invoices/998597326835.pdf'

least where are the storage from the STL Files ?

many questions :-)

Thanks

**Comment by squancy** [comment]
Sorry for the late response. I will add the necessary table to the SQL dump and e-invoices directory.

**Comment by squancy** [comment]
Hi,

Now you should be able to set up the project on your machine.
I have also updated the README file and added more detailed instructions.
